# Site settings
title: КД-ЕвроТранс
email: kdeurotrans@gmail.com

description: >
 ООО «КД-ЕвроТранс» - транспортно-логистическое предприятие.<br/>
 Выполнение перевозок грузов автомобильным транспортом в международном сообщении.<br/>
 13 тентованных автопоездов с полуприцепами типа штора и бортовыми полуприцепами. Объемом до 90 куб.м.<br/>
 География перевозок: Польша, Литва, Чехия, Словакия, Россия. Перевозки осуществляем транзитом через Калининградскую область.<br/>
 Груз застрахован. Оформлен полис страхования ответственности перевозчика на 10 000 000 рублей.

phone_number: +7 4012 641158
address: 236004 Россия, Калининградская область, город Калининград, улица Дзержинского 19
skype: ivekom

google_analytics: UA-27574192-2

baseurl: ""
url: "http://kd-eurotrans.com"

markdown: kramdown
